from __future__ import annotations

"""Pokémon X/Y Gen 6 location names.

IDs follow the Gen 6 XY location-text index used by the games/PKHeX.  Blank
entries in the source table are intentionally absent from this dictionary;
callers should use ``xy_location_name`` for a safe fallback.

The table is kept separate from ORAS because Gen 6 shares one text resource
but the Kalos and Hoenn location ranges are distinct.  This also prevents an
X/Y session from accidentally resolving an ID through the ORAS map table.
"""

XY_LOCATION_NAMES = {
    2: "Mystery Zone",
    4: "Faraway Place",
    6: "Vaniville Town",
    8: "Route 1",
    9: "Vaniville Pathway",
    10: "Aquacorde Town",
    12: "Route 2",
    13: "Avance Trail",
    14: "Santalune Forest",
    16: "Route 3",
    17: "Ouvert Way",
    18: "Santalune City",
    20: "Route 4",
    21: "Parterre Way",
    22: "Lumiose City",
    24: "Prism Tower",
    26: "Lysandre Labs",
    28: "Route 5",
    29: "Versant Road",
    30: "Camphrier Town",
    32: "Shabboneau Castle",
    34: "Route 6",
    35: "Palais Lane",
    36: "Parfum Palace",
    38: "Route 7",
    39: "Rivière Walk",
    40: "Cyllage City",
    42: "Route 8",
    43: "Muraille Coast",
    44: "Ambrette Town",
    46: "Route 9",
    47: "Spikes Passage",
    48: "Battle Chateau",
    50: "Route 10",
    51: "Menhir Trail",
    52: "Geosenge Town",
    54: "Route 11",
    55: "Miroir Way",
    56: "Reflection Cave",
    58: "Shalour City",
    60: "Tower of Mastery",
    62: "Route 12",
    63: "Fourrage Road",
    64: "Coumarine City",
    66: "Route 13",
    67: "Lumiose Badlands",
    68: "Route 14",
    69: "Laverre Nature Trail",
    70: "Laverre City",
    72: "Poké Ball Factory",
    74: "Route 15",
    75: "Brun Way",
    76: "Dendemille Town",
    78: "Route 16",
    79: "Mélancolie Path",
    82: "Frost Cavern",
    84: "Route 17",
    85: "Mamoswine Road",
    86: "Anistar City",
    88: "Route 18",
    89: "Vallée Étroite Way",
    90: "Couriway Town",
    92: "Route 19",
    93: "Grande Vallée Way",
    94: "Snowbelle City",
    96: "Route 20",
    97: "Winding Woods",
    98: "Pokémon Village",
    100: "Route 21",
    101: "Dernière Way",
    102: "Route 22",
    103: "Détourner Way",
    104: "Victory Road",
    106: "Pokémon League",
    108: "Kiloude City",
    110: "Battle Maison",
    112: "Azure Bay",
    114: "Dendemille Gate",
    116: "Couriway Gate",
    118: "Ambrette Gate",
    120: "Lumiose Gate",
    122: "Shalour Gate",
    124: "Coumarine Gate",
    126: "Laverre Gate",
    128: "Anistar Gate",
    130: "Snowbelle Gate",
    132: "Glittering Cave",
    134: "Connecting Cave",
    135: "Zubat Roost",
    136: "Kalos Power Plant",
    138: "Team Flare Secret HQ",
    140: "Terminus Cave",
    142: "Lost Hotel",
    144: "Chamber of Emptiness",
    146: "Sea Spirit’s Den",
    148: "Friend Safari",
    150: "Blazing Chamber",
    152: "Flood Chamber",
    154: "Ironworks Chamber",
    156: "Dragonmark Chamber",
    158: "Radiant Chamber",
    160: "Pokémon League Gate",
    162: "Lumiose Station",
    164: "Kiloude Station",
    166: "Ambrette Aquarium",
    168: "Unknown Dungeon",
}

XY_STARTER_LOCATION_ID = 10
XY_STARTER_LOCATION_NAME = XY_LOCATION_NAMES[XY_STARTER_LOCATION_ID]


def xy_location_name(location_id: int | None, fallback: str = "Unknown Location") -> str:
    if location_id is None:
        return fallback
    return XY_LOCATION_NAMES.get(int(location_id), fallback)
